In [1]:
import torch
from torch import nn

In [2]:
x = torch.randn(100,3)
layer = nn.Linear(3,5)
print(layer(x).shape)
print(layer.weight)
print(layer.bias)

torch.Size([100, 5])
Parameter containing:
tensor([[ 0.3121,  0.2780,  0.3568],
        [-0.4131,  0.3400,  0.5053],
        [ 0.4485, -0.2096,  0.1513],
        [-0.0468, -0.0712,  0.4967],
        [-0.4313,  0.4702, -0.3085]], requires_grad=True)
Parameter containing:
tensor([-0.4414, -0.4030, -0.3073, -0.2641, -0.0364], requires_grad=True)


In [3]:
x = torch.randn(2,5)
layer = nn.ReLU()
print(layer(x))

tensor([[0.0000, 1.4001, 0.8537, 0.9783, 0.0000],
        [0.9054, 2.4799, 0.0000, 0.0000, 0.9486]])


In [4]:
drop = nn.Dropout(p = 0.9)
x = torch.randn(3,7)
print(drop(x))

tensor([[ 0.0000, -0.0000,  0.0000, -0.0000, -0.0000, -0.0000,  0.0000],
        [-0.0000, -0.0000,  0.0000, -0.0000, -0.0000,  0.0000,  0.0000],
        [-0.0000, -0.0000,  0.0000,  0.0000, -2.4345,  1.1242, -0.0000]])


In [5]:
class sample_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.drop_layer = nn.Sequential(nn.Linear(5,7),
                                        nn.Dropout(p = 0.3))
    
    def forward(self, x) : 
        x = self.drop_layer(x)
        return x





In [6]:
model = sample_model()
model.train()
x = torch.randn(1,3,5)
print(model(x))

model.eval()
print(model(x))

tensor([[[-1.3121,  1.5797,  0.5429, -0.8620,  0.0000,  0.8697, -0.0000],
         [ 0.5265,  0.1062, -1.1971, -1.6104,  0.1599,  0.5543, -1.7973],
         [ 0.4454, -0.0000,  0.2729,  0.0000, -1.2009,  1.8162, -0.3800]]],
       grad_fn=<MulBackward0>)
tensor([[[-0.9184,  1.1058,  0.3800, -0.6034,  1.4874,  0.6088, -0.7523],
         [ 0.3686,  0.0744, -0.8380, -1.1273,  0.1119,  0.3880, -1.2581],
         [ 0.3118, -1.1337,  0.1911,  0.5079, -0.8406,  1.2713, -0.2660]]],
       grad_fn=<ViewBackward0>)


In [7]:
layer = nn.Conv2d(in_channels = 1, out_channels = 2, kernel_size = 3, stride = 1, padding =1) # stride = 1, padding = 0 이 default
layer(torch.randn(32,1,5,5)).shape

torch.Size([32, 2, 5, 5])

In [8]:
layer = nn.Conv2d(2,5,3, padding = 1)
layer(torch.randn(32,2,5,5)).shape

torch.Size([32, 5, 5, 5])

In [9]:
conv1 = nn.Conv2d(1,8,6, padding = 0)
x = torch.randn(32,1,28,28)
print(conv1(x).shape)

conv1 = nn.Conv2d(1,8,6, padding = 1)
x = torch.randn(32,1,28,28)
print(conv1(x).shape)

conv1 = nn.Conv2d(1,8,6, padding = 2)
x = torch.randn(32,1,28,28)
print(conv1(x).shape)

conv2 = nn.Conv2d(1,8,6, stride = 1)
x = torch.randn(32,1,28,28)
print(conv2(x).shape)

conv2 = nn.Conv2d(1,8,6, stride = 2)
x = torch.randn(32,1,28,28)
print(conv2(x).shape)

Maxpool = nn.MaxPool2d(kernel_size = 2, stride=(2,2))
x = torch.randn(32,1,28,28)
print(Maxpool(x).shape)

Maxpool = nn.MaxPool2d(kernel_size = 2, stride=(3,3))
x = torch.randn(32,1,28,28)
print(Maxpool(x).shape)

Maxpool = nn.MaxPool2d(kernel_size = 3, stride=(2,2))
x = torch.randn(32,1,28,28)
print(Maxpool(x).shape)

Maxpool = nn.MaxPool2d(kernel_size = 3, stride=(3,3))
x = torch.randn(32,1,28,28)
print(Maxpool(x).shape)

torch.Size([32, 8, 23, 23])
torch.Size([32, 8, 25, 25])
torch.Size([32, 8, 27, 27])
torch.Size([32, 8, 23, 23])
torch.Size([32, 8, 12, 12])
torch.Size([32, 1, 14, 14])
torch.Size([32, 1, 9, 9])
torch.Size([32, 1, 13, 13])
torch.Size([32, 1, 9, 9])


In [12]:
class CNN_test(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(1,8,6,stride=2)
        self.conv2 = nn.Conv2d(8,16,3,padding=1)
        self.Maxpool2 = nn.MaxPool2d(2)
        self.fc = nn.Linear(16*6*6,10)

    def forward(self,x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.Maxpool2(x)
        x = torch.flatten(x,start_dim=1)
        x = self.fc(x)
        return x


input = torch.randn(32,1,28,28)
model = CNN_test()
print(model(input).shape)


torch.Size([32, 10])


In [14]:
maxpool = nn.MaxPool2d(2)
x = torch.randn(1,1,6,6)
print(x)
print(maxpool(x))
print(maxpool(x).shape)
print(maxpool(torch.randn(32,3,6,6)).shape)

tensor([[[[-1.4959, -0.5060,  1.2323,  0.9275,  1.0041, -0.6138],
          [ 1.6373,  0.0148, -1.2998, -1.2237,  0.0248,  1.2402],
          [ 0.9295,  0.7086, -1.7506, -0.2206,  0.5833, -0.1521],
          [-0.8119, -1.2731,  1.3403,  0.4768, -0.4384, -1.2026],
          [-1.3751,  0.3537, -0.2975, -0.4778,  0.6652, -0.3907],
          [ 0.9299, -0.2858, -0.1937, -0.4493, -1.0505, -0.7770]]]])
tensor([[[[ 1.6373,  1.2323,  1.2402],
          [ 0.9295,  1.3403,  0.5833],
          [ 0.9299, -0.1937,  0.6652]]]])
torch.Size([1, 1, 3, 3])
torch.Size([32, 3, 3, 3])


In [15]:
avgpool = nn.AvgPool2d(2)
x = torch.randn(1,1,6,6)
print(x)
print(avgpool(x))
print(avgpool(x).shape)
print(avgpool(torch.randn(32,3,6,6)).shape)

tensor([[[[-0.5209,  1.1112,  0.0515,  0.8734, -0.5235, -0.8104],
          [ 0.6475,  0.7471, -0.0237, -1.2280, -0.2619,  1.0148],
          [-0.9916,  0.9160, -1.7326,  0.2375, -0.1339,  0.4796],
          [-1.3781, -0.4739,  0.8087,  0.2355,  0.0241,  1.0317],
          [ 0.7339,  0.3297,  0.1348, -0.3936,  0.6589,  1.0277],
          [-0.6113, -1.1428, -0.4245,  0.9089,  1.6228, -0.7615]]]])
tensor([[[[ 0.4962, -0.0817, -0.1453],
          [-0.4819, -0.1127,  0.3504],
          [-0.1726,  0.0564,  0.6370]]]])
torch.Size([1, 1, 3, 3])
torch.Size([32, 3, 3, 3])


In [28]:
# ModuleList와 Sequential의 차이 -> ModuleList는 수정이 쉽고 U-Net 같은 경우 Sequential 사용 불가

import torch
from torch import nn, optim

fc = nn.Linear(3,3)
layers = nn.ModuleList([fc for _ in range(5)])  # forward 내장 X 개별으로 저장하는 느낌
print(layers)
layers2 = nn.Sequential(*[fc for _ in range(5)])  # forward 내장 O 통으로 저장하는 느낌

print(layers2)

x = torch.randn(1,3)
for layer in layers :
    x = layer(x)
print(x)


print(layers2(torch.randn(1,3)))




ModuleList(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
tensor([[-0.5785,  0.8591,  0.3644]], grad_fn=<AddmmBackward0>)
tensor([[ 0.5331, -0.4078,  0.4334]], grad_fn=<AddmmBackward0>)


In [33]:
# 그냥 리스트 쓰지 왜 nn.ModuleList를 쓸까?

class testNet(nn.Module):
    def __init__(self):
        super().__init__()
        #self.Module_List = [nn.Linear(3,3), nn.Linear(3,3)]  <- 일반 List하면 등록이 안됨. 최적화도 안됨
        self.Module_List = nn.ModuleList([nn.Linear(3,3), nn.Linear(3,3)])
    def forward(self, x):
        for layer in self.Module_List :
            x = layer(x)
        return x


model = testNet()
print(model(torch.randn(1,3)))


for m in model.Module_List :
    print(m)


# optimizer = optim.Adam(model.parameters(), lr = 0.01)    <- 일반 List로 하면 에러뜸

tensor([[ 0.9575, -0.9300, -0.3027]], grad_fn=<AddmmBackward0>)
Linear(in_features=3, out_features=3, bias=True)
Linear(in_features=3, out_features=3, bias=True)
