In [3]:
import torch
from torch import nn

fc1 = nn.Linear(1,3)
fc2 = nn.Linear(3,1)

x = torch.tensor([1.])
x = fc1(x)
print(x)
x = fc2(x)
print(x)

model = nn.Sequential(fc1, fc2)
x = torch.tensor([1.])
model(x)

tensor([1.6052, 0.3888, 1.4388], grad_fn=<AddBackward0>)
tensor([-0.3056], grad_fn=<AddBackward0>)


tensor([-0.3056], grad_fn=<AddBackward0>)

In [6]:
model = nn.Sequential(nn.Linear(2,5),
                      nn.Linear(5,10),
                      nn.Linear(10,10),
                      nn.Linear(10,3))

x = torch.randn(2)
model(x)

x = torch.randn(5,2) # 5개의 data, 근데 data 한 개가 두 개의 값을 가지고 있음

print(x)
print(model(x))
# 키, 몸무게 값을 다섯 사람 데이터에 대해서 통과 시킨것


tensor([[ 1.3936, -0.0278],
        [-0.4342,  0.3610],
        [ 1.9145,  1.6117],
        [ 0.3832,  1.7758],
        [ 0.4291, -1.0136]])
tensor([[ 0.0793,  0.3866, -0.0977],
        [ 0.1716,  0.2888, -0.2284],
        [-0.0717,  0.4450,  0.0194],
        [ 0.0171,  0.3603, -0.0975],
        [ 0.2128,  0.3143, -0.2210]], grad_fn=<AddmmBackward0>)


In [8]:
import torch
from torch import nn


class MyModel(nn.Module) :
    def __init__(self):
        super().__init__()

        self.fc1 = nn.Linear(2,5)
        self.fc2 = nn.Linear(5,10)
        self.fc3 = nn.Linear(10,3)

    def forward(self, x) :
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        x = torch.heaviside(x, values = torch.tensor([0.5]))
        return x

model = MyModel()
x = torch.randn(5,2)
y = model(x)
print(y)
print(model)

print(model.fc1.weight)
print(model.fc1.bias)


tensor([[1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 1., 1.],
        [0., 1., 1.]], grad_fn=<NotImplemented>)
MyModel(
  (fc1): Linear(in_features=2, out_features=5, bias=True)
  (fc2): Linear(in_features=5, out_features=10, bias=True)
  (fc3): Linear(in_features=10, out_features=3, bias=True)
)


In [17]:
import torch
from torch import nn


class MyModel2(nn.Module) :
    def __init__(self):
        super().__init__()

        self.fcs = nn.Sequential(nn.Linear(2,5),
                                 nn.Linear(5,10),
                                 nn.Linear(10,3))

    def forward(self, x) :
        x = self.fcs(x)
        x = torch.heaviside(x, values = torch.tensor([0.5]))
        return x

model2 = MyModel2()
x = torch.randn(5,2)
y = model2(x)
print(y)

print(model2.fcs[0].weight)
print(model2.fcs[0].bias)

tensor([[1., 1., 0.],
        [0., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.],
        [1., 0., 0.]], grad_fn=<NotImplemented>)
Parameter containing:
tensor([[-0.3550,  0.6449],
        [-0.6662,  0.0655],
        [ 0.4360,  0.6975],
        [-0.4478,  0.3393],
        [-0.1087,  0.6901]], requires_grad=True)
Parameter containing:
tensor([ 0.3492, -0.0568,  0.2115,  0.4148, -0.0874], requires_grad=True)


In [21]:
# 파라미터 수 구하기

num = 0

for param in model.parameters():
    if param.requires_grad:
        num+= param.numel()

print(num)

num = 0

for param in model2.parameters():
    if param.requires_grad:
        num+= param.numel()

print(num)



108
108
